#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='code'
export VISUAL='code'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi


export CLIENT_TOOLS_ROOT=$HOME/Library/Android/
export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
export ANDROID_HOME=$HOME/Library/Android/
# Export ANDROID_NDK_ROOT to tell the makefiles where it can
# find the cross-compilation tools.
export ANDROID_NDK_ROOT=$HOME/Library/Android/android-ndk-r11c
export ANDROID_NDK=$HOME/Library/Android/android-ndk-r11c
# Update your path so you can call adb, android and other 
# binaries in the SDK.
export PATH=$PATH:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/tools/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_NDK_ROOT
# This this export of FLX_TARGET tells the Makefiles to build 
# Android - it's the only target we use these days.
export FLX_TARGET=Android 

 
#Android requires JDK8
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home
 
# This export of SECURITY_CORE_PATH tells the makefiles where it
# can find the security project in order to build the last version
# of the library.
export SECURITY_CORE_PATH=$HOME/Projects/security 

# may or may not need these. may need to download ndk directly from website
# export ANDROID_NDK=$HOME/Library/Android/sdk/ndk-bundle/android-ndk-r11c
# may need to add the ndk directory to PATH